#include "annabelle_chat.h"
#include "ai.h"

/*
 * Annabelle.AI terminal chat interface.
 *
 * IMPORTANT:
 * This file intentionally does not touch:
 *   - RTL8139
 *   - Ethernet
 *   - ARP
 *   - IPv4
 *   - UDP
 *   - TCP
 *   - HTTP
 *   - MeetOS shell implementation
 *
 * It is only a UI layer around the existing AI subsystem.
 */

#define ANNABELLE_INPUT_SIZE 128

#define KEY_NONE   0

extern char keyboard_read(void);

extern void print(const char *text);
extern void print_char(char c);
extern void clear_screen(void);
extern void cursor_shape(void);

static int annabelle_string_equal(
    const char *a,
    const char *b
)
{
    int i = 0;

    while (a[i] != '\0' && b[i] != '\0')
    {
        if (a[i] != b[i])
            return 0;

        i++;
    }

    return a[i] == '\0' && b[i] == '\0';
}


/*
 * Read one line using the existing MeetOS PS/2 keyboard driver.
 *
 * We deliberately keep this independent from read_command().
 * Therefore the existing MeetOS command editor remains untouched.
 */
static void annabelle_read_line(char *buffer)
{
    int length = 0;
    char c;

    buffer[0] = '\0';

    while (1)
    {
        c = keyboard_read();

        if (c == KEY_NONE)
            continue;

        /*
         * ENTER
         */
        if (c == '\n')
        {
            buffer[length] = '\0';
            print("\n");
            return;
        }

        /*
         * BACKSPACE
         */
        if (c == '\b')
        {
            if (length > 0)
            {
                length--;
                buffer[length] = '\0';

                /*
                 * print_char('\b') already moves the VGA cursor
                 * backwards and clears the character.
                 */
                print_char('\b');
            }

            continue;
        }

        /*
         * Printable ASCII.
         */
        if (c >= 32 && c <= 126)
        {
            if (length < ANNABELLE_INPUT_SIZE - 1)
            {
                buffer[length] = c;
                length++;

                buffer[length] = '\0';

                print_char(c);
            }
        }
    }
}


/*
 * Opening screen.
 */
static void annabelle_show_intro(void)
{
    clear_screen();
    cursor_shape();

    print("+==============================================================================+\n");
    print("|                              ANNABELLE.AI                                  |\n");
    print("|                         PRIVATE CONVERSATION                               |\n");
    print("+==============================================================================+\n");
    print("\n");

    print("                    entering Annabelle.AI...\n");
    print("\n");
    print("                    \"The conversation has been waiting.\"\n");
    print("\n");

    print("                    Initializing...\n");
    print("                    Loading memory...\n");
    print("                    Restoring conversation...\n");
    print("\n");
    print("                    Annabelle.AI is ready.\n");
    print("\n");

    print("+==============================================================================+\n");
    print("\n");

    /*
     * Existing AI history is displayed by the existing subsystem.
     * We do not create a second competing history system here.
     */
    ai_print_history();

    print("\n");
    print("-------------------------------------------------------------------------------\n");
    print(" Annabelle > Hello. I'm Annabelle.\n");
    print("              What would you like to talk about?\n");
    print("-------------------------------------------------------------------------------\n");
    print("\n");
}


/*
 * Annabelle chat mode.
 *
 * &prompt exits this mode and returns to MeetOS.
 */
static void annabelle_chat_loop(void)
{
    char message[ANNABELLE_INPUT_SIZE];

    while (1)
    {
        print("You       > ");

        annabelle_read_line(message);

        /*
         * Empty message.
         */
        if (message[0] == '\0')
        {
            continue;
        }

        /*
         * Leave Annabelle and return to MeetOS.
         */
        if (annabelle_string_equal(message, "&prompt"))
        {
            print("\n");
            print("Leaving Annabelle.AI...\n");
            print("Conversation remains in memory.\n");
            print("Returning to MeetOS...\n");
            print("\n");

            return;
        }

        /*
         * A small visual transition before the existing AI request.
         *
         * The actual answer is still generated by ai_prompt().
         * We are NOT replacing the AI engine with if/else logic.
         */
        print("\n");
        print("Annabelle > thinking...\n");
        print("\n");

        /*
         * Use the existing Annabelle subsystem.
         *
         * This is the critical safety point:
         * networking/HTTP/TCP code is not duplicated here.
         */
        ai_prompt(message);

        print("\n");
    }
}


/*
 * Shell command:
 *
 *     &annabelle
 *
 * The shell passes the text after the command to us.
 */
void annabelle_chat_command(char *arguments)
{
    (void)arguments;

    annabelle_show_intro();
    annabelle_chat_loop();

    /*
     * Clear the cursor state so MeetOS can continue normally.
     */
    cursor_shape();
}
